# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

service: serverless-justindb

provider:
  name: aws
  runtime: nodejs6.10

functions:
  get:
    handler: handler.get
    events:
      - http:
          path: justindb-get
          method: get
          cors: true
  put:
    handler: handler.put
    events:
      - http:
          path: justindb-put
          method: get
          cors: true